[features]
seeds = false
skip-lint = false
[programs.localnet]
test_program = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "node tests/test-program.ts"
 